services:
  postgres:
    image: postgres:17
    container_name: may-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    ports:
      - "7000:5432"
    volumes:
      - /home/developer/volume/may-postgres-data:/var/lib/postgresql/data
